### ISSUE TITLE
color/var bug

### ISSUE THREAD

**Issue by MoOx** [MoOx/postcss-cssnext#25]
``` css
:root {
    --base-link-color: #000;
    --base-link-color-hover: color(var(--base-link-color) lightness(+10%));
}
a {
    color : var(--base-link-color-hover);
}
```

should yields into something like:

``` css
a {
 color: rgb(255, 51, 51);
}
```

And not throw an error: `Error: Unable to parse color from string var(--base-link-color)`
