### ISSUE TITLE
Can't use variable in media query

### ISSUE THREAD

**Issue by niftylettuce** [MoOx/postcss-cssnext#253]
The other day I tried to do this, I had a note to file an issue:

```css
:root {
  --tabletWidth: 768px;
}

@custom-media --small (width < --tabletWidth);

@media (--small) {
  h1 {
    max-width: 100%;
    background-size: contain;
  }
}
```

Outputs:

```css
@media (width < var(--tabletWidth)) {

  #app h1 {
    max-width: 100%;
    background-size: contain;
  }
  }

```

**Comment by MoOx** [comment]
var() depend on custom props, which depends on the dom. Please use `@custom-media` for this.

**Comment by MoOx** [comment]
Please use the chat for support and question.

**Comment by niftylettuce** [comment]
I did use @custom-media -- I think the docs are just super confusing.

All I want to do is define a mixin-like media query that uses variables.

Can I not do this?

**Comment by niftylettuce** [comment]
I see what you mean - the variables depend on DOM - so I can't use them inside a media query?

Anyways, I went ahead and used https://github.com/postcss/postcss-simple-vars for media queries with variables (or anyone else that sees this issue)/

**Comment by MoOx** [comment]
Docs are CSS specs.

```css
:root {
  --tabletWidth: 768px;
}

@custom-media --small (width < --tabletWidth);

@media (--small) {
  h1 {
    max-width: 100%;
    background-size: contain;
  }
}
```

Output

```css
:root {
  --tabletWidth: 768px;
}

@custom-media --small (width < --tabletWidth);

@media (--small) {
  h1 {
    max-width: 100%;
    background-size: contain;
  }
}
```

Nothing weird:
- You don't use var() in your custom-media
- var() cannot be used here anyway since :root{} is a dom element (html).

Just use this

```
@custom-media --small (width < 768px);

@media (--small) {
  h1 {
    max-width: 100%;
    background-size: contain;
  }
}
```

It's how you should use custom-media.
