### ISSUE TITLE
Group media queries

### ISSUE THREAD

**Issue by dhoko** [MoOx/postcss-cssnext#27]
CSS next : 

``` css
/* custom media query usage */
@media (--viewport-medium) {
  body { font-size: calc(var(--fontSize) * 1.2); }
}

/* custom media query usage */
@media (--viewport-medium) {
  p { font-size: calc(var(--fontSize) * 1.2); }
}
```

CSSnext generates

``` css
/* custom media query usage */
@media (max-width: 50em) {
  body { font-size: 1.2rem; }
}


/* custom media query usage */
@media (max-width: 50em) {
  p { font-size: 1.2rem; }
}
```

It would be nice if media queries could be grouped: 

``` css
/* custom media query usage */
@media (max-width: 50em) {
  body { font-size: 1.2rem; }
  p { font-size: 1.2rem; }
}
```

No ?
