### ISSUE TITLE
Nest selectors is transpiled strangely

### ISSUE THREAD

**Issue by AJIh** [MoOx/postcss-cssnext#275]
This is my webpack config.

```javascript

...

var postCSSConfig = function(webpack) {
  return [
    require('postcss-import')({
      path: path.join(__dirname, '..', 'app', 'css'),
      addDependencyTo: webpack
    }),
    require('postcss-cssnext')(),
    require('postcss-reporter')({
      clearMessages: true
    })
  ];
};

module.exports = {
    ...
    entry: {
      app: ['./client', hotMiddlewareScript]
    },
    module: {
      loaders: commonLoaders.concat([
        { test: /\.css$/,
          loader: 'style!css?module&localIdentName=[name]__[local]___[hash:base64:5]&importLoaders=1!postcss'
        }
      ])
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin(),
        new webpack.DefinePlugin({
          __DEVCLIENT__: true,
          __DEVSERVER__: false
        })
    ],
    postcss: postCSSConfig
};
```

And my css file with nesting selector:

```css
@import '../settings.css';
@import '../common/colors.css';

.login {
  width: 420px;
  margin: 0 auto;
  background-color: var(--color-athens-gray);
  border: 2px solid var(--color-mercury);
  border-radius: var(--global-radius);
}

  .waiting {
    .loading {
      display: block;
    }
  }

...
```

It is transpiled into:

```css
.login__login___2D52F {
  width: 420px;
  margin: 0 auto;
  background-color: #f5f5f6;
  border: 2px solid #e3e3e3;
  border-radius: 4px;
}

.login__waiting___1IvY6 {
    .login__loading___eyJ6c {
      display: block;
    }
  }
```

**Comment by AJIh** [comment]
Oops. I did not notice the comments in the doc. Sorry. 😳

```css
  /* direct nesting (& MUST be the first part of selector)*/
  & span {
    color: white;
  }
```

Please close the issue.
