### ISSUE TITLE
Output has Duplicate Empty Property when Using `var()`

### ISSUE THREAD

**Issue by ryanfitzer** [MoOx/postcss-cssnext#276]
Using the default configuration, I'm getting a duplicate property with an empty value.

Before:

```css
a {
	color: var( --global-color-links );
}
```

After:

```css
a {
	color:  ;
	color: #c53e3e;
}
```

**Comment by MoOx** [comment]
The last space before the parenthesis is causing this tiny bug.
No problem with the code below

```css
:root {
  --global-color-links: #c53e3e;
}

a {
    color: var(--global-color-links);
}
```

The bug has to be fixed in https://github.com/postcss/postcss-custom-properties
