### ISSUE TITLE
Missing semicolon on nesting selectors with &

### ISSUE THREAD

**Issue by delibash** [MoOx/postcss-cssnext#277]
I am having a strange issue with a missing semicolon when using nesting.

For instance, if I write this code:

```css
.sticky__element {
  position: relative;
  background: yellow;
  &--fixed {
    position: fixed;
    background: red;
  }
}
```

I will get the following code:

```css
.sticky__element {
  position: relative;
  background: yellow
}
.sticky__element--fixed {
  position: fixed;
  background: red
}
```

The last line is missing a semicolon. I am using Webpack with ExtractTextPlugin.
