### ISSUE TITLE
:matches(element)

### ISSUE THREAD

**Issue by stevenvachon** [MoOx/postcss-cssnext#287]
```css
.class {
  &:matches(element) {
    property: value;
  }
}
```
produces:
```css
.classelement {
  property: value;
}
```
when it *should* produce:
```css
element.class {
  property: value;
}
```
