### ISSUE TITLE
nested selectors doesn't with custom selectors

### ISSUE THREAD

**Issue by yordis** [MoOx/postcss-cssnext#297]
I am working in some project and I tried to use custom selector with nested selectors and It didn't work. This is the code used.
```css
@custom-selector :--boa-button .boa-button;

:--boa-button {
  display: inline-block;

  &--pressed,
  &--focused {
    background: red;
  }
}
```

CSS Output
```css
.boa-button {
   display: inline-block;
}

// Notice that is repeat twice the selector
:--boa-button--pressed,
  :--boa-button--focused,
  :--boa-button--pressed,
  :--boa-button--focused {
  background: red
}
```
Console Output
```bash
The selector ':--boa-button--pressed,  :--boa-button--focused' is undefined
```
