### ISSUE TITLE
Support nested media queries

### ISSUE THREAD

**Issue by MoOx** [MoOx/postcss-cssnext#30]
Nested media queries are working on latest Firefox, Chrome & Safari 8, but not on IE.

We should make this work by moving rules into new media queries using `and`.

http://jsbin.com/kafoxi/1/edit

**Comment by lyzadanger** [comment]
You can also nest `@supports` per the conditional module that covers nesting `@media` (any combination can be nested): http://dev.w3.org/csswg/css-conditional-3/

http://jsbin.com/xoqeso/2/edit

**Comment by idoo** [comment]
yes, i think it's really cool feature

**Comment by Semigradsky** [comment]
Silly example (https://jsbin.com/sakuxiz/edit?css,output):
```css
@media screen {
  html {
    background: yellow;  
  }
  
  @media (max-width: 1100px) {
    html, body {
      background: green
    }
  }  
  
  body {
    background: red;
  }
}
```
We can't move media without ruining styles.
