### ISSUE TITLE
[doc] @nest with several rules/selectors

### ISSUE THREAD

**Issue by brillout** [MoOx/postcss-cssnext#316]
From reading the doc I was expecting following to work

``` css
div {
  @nest .c1 &,
  @nest .c2 & {
    color: red;
  }
}
```

but the correct usage is

``` css
div {
  @nest
  .c1 &,
  .c2 & {
    color: red;
  }
}
```

A note or example about that would have saved me 30mn.

Thanks for `postcss-cssnext` btw, I really like it.

(cross issue: https://github.com/jonathantneal/postcss-nesting/issues/22)
