### ISSUE TITLE
(Custom selectors + Nesting) "&" doesn't interpolate as expected

### ISSUE THREAD

**Issue by izolate** [MoOx/postcss-cssnext#321]
Hi, I'm not sure if the following is the proper behaviour, but I'm having trouble with string interpolation with the nested `&` selector:

```css
@custom-selector :--button .btn;

:--button {
  &--danger {
    background-color: red;
  }
}
```

Outputs:
```css
:--button--danger {
  background-color: red
}
```

Expected output:
```css
.btn--danger {
  background-color: red
}
```

Any help is greatly appreciated.
