### ISSUE TITLE
Preserve custom properties not working.

### ISSUE THREAD

**Issue by sunglee** [MoOx/postcss-cssnext#324]
Based on the documentation, it says you can preserve custom properties when exporting.

For example, from the following code:

``` css
//postcss
:root {
  --color-main: #f00;
}

.button {
  background: var(--color-main);
}
```

What I expected was:

``` css
.button {
  background: #f00;
  background: var(--color-main);
}
```

What I got after processing was without preserving custom properties:

``` css
.button {
  background: #f00;
}
```

I have a following gulp task:

``` js
gulp.task('styles', () => {
  const processors = [
    cssnext({
      features: {
        customProperties: {
          preserve: true,
          appendVariables: true
        }
      }
    }),
  ];
  return gulp.src(['*.css'
  ])
    .pipe(postcss(processors))
    .pipe(gulp.dest('.tmp/css'));
});
```

Anything I am missing? Thanks for your comments.
