### ISSUE TITLE
Unclear if there is an option to output the custom properties as just fallbacks

### ISSUE THREAD

**Issue by marcofugaro** [MoOx/postcss-cssnext#336]
Browser are starting to support much more custom properties stuff, I want to be able to play around with javascript and those, and just display the CSS fallback on browser that don't support them.

From the playground, I noticed every custom property gets compiled.

Is it possible to to with cssnext or should I just use autoprefixer for the fallbacks? Can autoprefixer do that?

**Comment by MoOx** [comment]
See usage#features section in the docs to pass options http://cssnext.io/usage/#features

Feel free to update the docs to add more clear example!

**Comment by marcofugaro** [comment]
I did not make myself clear,
this is the **input**:
```css
:root {
  --mainColor: #123456;
}
body {
  color: var(--mainColor);
}
```
And right now the **output** is:
```css
body {
  color: #123456;
}
```
I want the option to be able to **output** this:
```css
:root {
  --mainColor: #123456;
}
body {
  color: #123456;
  color: var(--mainColor);
}
```
in a "fallback" way, since the main browsers already support custom properties.

How do I do it? If I can't do it because it would case css bloat or some other reason a note in documentation would be nice.
Yes I know I can disable the compilation of some features through the options. Yes I can help you with the documentation if possible.
