### ISSUE TITLE
rem > px fallback always outputting (require browserlist latest version?)

### ISSUE THREAD

**Issue by mrcsmcln** [MoOx/postcss-cssnext#340]
**Input**:

`package.json`:
```json
{
  ...
  "browserslist": "last 1 chrome version"
  ...
}
```

`style.css`:
```css
div {
  margin-bottom: 1rem;
}
```

**Output**

```css
div {
  margin-bottom: 16px;
  margin-bottom: 1rem;
}
```

Can anyone else confirm this?
