### ISSUE TITLE
Var fallback value leads to double output

### ISSUE THREAD

**Issue by lukasoppermann** [MoOx/postcss-cssnext#356]
Hey, this is the actual problem from #354.

When using a fallback value for a custom property like `width: var(--number, 100px)` the output is this:

```css
:root{
  --number: 10px;
}

.element{
   width: var(--number, 100px);
}
```

Gets converted to:

```css
.element{
   width: 10px;
   width: 100px;
}
```

I am using the latest post-css `2.10.0` with gulp. Please let me know if you need any other input.

**Comment by MoOx** [comment]
It's not a bug, it's a feature.
Imagine this

```css
.element{
   width: var(--whoknows, 100px);
}

/* in another file */

:root{
  --whoknows: lol;
}
```

You will get

```css
.element{
   width: 10px;
   width: lol;
}
```

So fallback is here to be a... fallback! It will be dangerous and unsafe to try to optimize by if detecting value is "valid" or not...

**Comment by Semigradsky** [comment]
@MoOx 
correctly should be
```css
.element{
   width: 100px;
   width: 10px;
}
```

**Comment by MoOx** [comment]
Yeah I guess the guy made an error, the playground gives this result :)

**Comment by Semigradsky** [comment]
@lukasoppermann I tried your config from 354 and received correct output:
```css
.element{width:100px;width:10px}
```

**Comment by MoOx** [comment]
@Semigradsky I think what @lukasoppermann would like is this:

```css
.element{width:10px}
```

because 10px is valid
