### ISSUE TITLE
Animation shorthand automatically wraps animation-name with :local

### ISSUE THREAD

**Issue by publicJorn** [MoOx/postcss-cssnext#360]
My css module:

```css
@keyframes loader {
  100% { opacity: 1; }
  90% { opacity: .87; }
  80% { opacity: .74; }
  70% { opacity: .61; }
  60% { opacity: .48; }
  50% { opacity: .35; }
  40% { opacity: .35; }
  30% { opacity: .35; }
  20% { opacity: .35; }
  10% { opacity: .35; }
}

.loader path:nth-of-type(1) { animation: 1.0s loader 0.0s infinite; }
/* ...etc */
```

output:

```css
@-webkit-keyframes ResultLoading__loader {
  100% { opacity: 1; }
  /* ...truncated for easier reading */
}

@keyframes ResultLoading__loader {
  100% { opacity: 1; }
  /* ...truncated for easier reading  */
}

.ResultLoading__loader path:nth-of-type(1) {
  -webkit-animation: 1.0s :local(loader) 0.0s infinite;
  animation: 1.0s :local(loader) 0.0s infinite;
}
```

Notice the `:local(loader)`.

In [this css-loader issue](https://github.com/webpack-contrib/css-loader/issues/264) someone hinted this might work:

```css
@keyframes :local(loader) {
 /* ...etc */
}
```

But it doesn't work for me. The keyframes keep the module prefix `ResultLoading__`.

When writing down every animate property separately, it does work (in development; minification might still mess it up though, if it combines them. didn't try yet)

```css
.loader path:nth-of-type(1) {
  animation-duration: 1.0s;
  animation-name: taste-profile-loader;
  animation-delay: 0.0s;
  animation-iteration-count: infinite;
}
```

Output: 

```css
@-webkit-keyframes ResultLoading__loader {
  100% { opacity: 1; }
  /* ...truncated for easier reading */
}

@keyframes ResultLoading__loader {
  100% { opacity: 1; }
  /* ...truncated for easier reading  */
}

.ResultLoading__loader path:nth-of-type(1) {
  /* omitted -webkit props for easier reading */
  animation-duration: 1.0s;
  animation-name: ResultLoading__loader;
  animation-delay: 0.0s;
  animation-iteration-count: infinite;
}
```

Is this a bug, or am I forgetting something?
