### ISSUE TITLE
Nesting multiple rule-sets fail

### ISSUE THREAD

**Issue by arktype** [MoOx/postcss-cssnext#376]
When adding more than one nested rule-set, only the first is being output.

Input:
````css
.videos.list {
	& ul, & li {
		margin: 0;
	}
	& li {
		padding: 10px;
	}
}
````
Expected output:
````css
.videos.list {
}
.videos.list ul, .videos.list li {
		margin: 0;
}
.videos.list li {
		padding: 10px;
}
````
Actual output:
````css
.videos.list {
}
.videos.list ul, .videos.list li {
		margin: 0;
}
````
