### ISSUE TITLE
nest parent selector

### ISSUE THREAD

**Issue by Shyam-Chen** [MoOx/postcss-cssnext#378]
```styl
.foo {
  &__bar {
    width: 10px;

    ^[0]:hover & {
      width: 20px;
    }
  }
}
```

```css
.foo__bar {
  width: 10px;
}
.foo:hover .foo__bar {
  width: 20px;
}
```
