### ISSUE TITLE
Bug with nesting

### ISSUE THREAD

**Issue by sc0rp10** [MoOx/postcss-cssnext#389]
Hi, I found strange bug that I cannot reproduce in playground.
I have following `foo.css`:
```css
.foo {
    color: #000;
    &__bar {
        color: #aaa;
    }

    &__baz {
        color: #bbb;

        &:hover {
            color: #ccc;
        }
    }
}

```
And next `gulpfile.js`:
```js
const gulp = require("gulp");
const postcss = require("gulp-postcss");

gulp.task('css', function () {
    return gulp.src('foo.css')
        .pipe( postcss([ require('postcss-cssnext') ]) )
        .pipe( gulp.dest('build/') );
});

```
`package.json`:
```json
{
  "dependencies": {
    "gulp": "^3.9.1",
    "gulp-postcss": "^7.0.0",
    "postcss-cssnext": "^2.11.0"
  }
}
```
I expect:
```css
.foo {
    color: #000
}
.foo__bar {
    color: #aaa
}
.foo__baz {
    color: #bbb
}
.foo__baz:hover {
    color: #ccc
}
```
But I found:
```css
.foo__baz {
        color: #bbb;

        &:hover {
            color: #ccc;
        }
}.foo {
    color: #000
}

.foo__bar {
        color: #aaa;
}

```

What am I doing wrong?
Can you please help me with the right setup?
Thanks!
