### ISSUE TITLE
@apply only works once

### ISSUE THREAD

**Issue by iamso** [MoOx/postcss-cssnext#397]
I'm having the issue that `@apply` is only working once and after that it seems to be ignored. For example:

**input:**
```css
:root {
  --text-hide: {
    font: 0/0 a;
    color: transparent;
    text-shadow: none;
    background-color: transparent;
    border: 0;
  };
}
.selector-one {
  @apply --text-hide;
}
.selector-two {
  @apply --text-hide;
}
```

**output:**
```css
.selector-one {
    font: 0/0 a;
    color: transparent;
    text-shadow: none;
    background-color: transparent;
    border: 0;
}
.selector-two {}
```

In the first one it works, but the second time it's empty. This used to work (in another project with probably different package versions).

This is the PostCSS setup in Gulp:

```javascript
.pipe(require('gulp-postcss')([
  require('postcss-import'),
  require('postcss-mixins'),
  require('postcss-cssnext')({
    diff: true,
    map: false,
    remove: false,
  }),
  require('postcss-nested'),
  require('postcss-discard-comments')({removeAll: true}),
  require('postcss-reporter')({ clearMessages: true }),
], {syntax: require('postcss-scss')}))
```

And these are the package versions:

```json
"gulp-postcss": "^7.0.0",
"postcss-cssnext": "^2.11.0",
"postcss-discard-comments": "^2.0.4",
"postcss-import": "^10.0.0",
"postcss-mixins": "^6.0.1",
"postcss-nested": "^2.0.2",
"postcss-reporter": "^4.0.0",
"postcss-scss": "^1.0.2",
```

Does anyone have an idea what could cause this issue?

Thanks
Steve
