### ISSUE TITLE
3.0.0 CSS Variable hyphen compiling change

### ISSUE THREAD

**Issue by dangodev** [MoOx/postcss-cssnext#403]
Take 2 CSS variables:
```
:root {
  --space: 32px;
  --space-075: 24px;
}
```
In both 2.9.x and 3.0.0, the variables compile correctly when used by themselves. However, something interesting happens when you try and invert those values:

**2.9.x**
```
margin-left: -var(--space); // -32px
margin-bottom: -var(--space); // -24px
```

**3.0.0**
```
margin-left: -var(--space); // -32px
margin-bottom: -var(--space); // 24px !!!
```

I rolled back my version to double-test, and confirmed it’s compiling differently with 3.0.0. Am I missing something? Are hyphens not part of the variable spec? Is it bad practice to prepend/append CSS variables?

**Comment by MoOx** [comment]
Please provide correct examples.
I guess you are providing this

```css
:root {
  --space: 32px;
  --space-075: 24px;
}

body {
  margin-left: -var(--space);
  margin-bottom: -var(--space-075);
}
```

and expect this

```css
body {
  margin-left: -32px;
  margin-bottom: -24px;
}
```

If that's the case (cause I don't understand the -075 purpose otherwise), it's working this way on the playground http://cssnext.io/playground/
