### ISSUE TITLE
direct nesting stops working after rule with @nest syntax

### ISSUE THREAD

**Issue by ctumolosus** [MoOx/postcss-cssnext#406]
Given the following CSS snippet:

```css
.icon {
  
  @nest .small & {
    font-size: 16px;
  }
}

.positive {
  background-color: green;

  &.outline {
    background-color: transparent;
  }
}
```

I expected the nested `.positive.outline` rule to be transformed to:

```css
.positive.outline {
  background-color: transparent;
}
```

But it fails silently. 

You can also reproduce this by copy/pasting the snippet into the [cssnext playground](http://cssnext.io/playground/).

However, if you add anything (including comments) to the empty `.icon`  rule it works as expected:

```css
.icon {
  /* whatever */

  @nest .small & {
    font-size: 16px;
  }
}

.positive {
  background-color: green;

  &.outline {
    background-color: transparent;
  }
}
```

**Comment by equinusocio** [comment]
I can confirm, but why you should write
```css
.icon {
  @nest .small & {
    font-size: 16px;
  }
}
```

If `.icon` doesn't have any declarations you can just write `.small .icon` or `.small {  & .icon {} }`
