### ISSUE TITLE
rem fallback doesn't work in media queries

### ISSUE THREAD

**Issue by julmot** [MoOx/postcss-cssnext#407]
When specifying `rem` a `px` fallback is generated, but not inside `@media` queries, as this screenshot demonstrates:

![2017-07-19 14_06_12-](https://user-images.githubusercontent.com/8310677/28366134-aa2dc91e-6c8b-11e7-9dbf-db4bdfc88f31.png)

**Comment by RyanZim** [comment]
Confirmed.

Input:
```css
@media (min-width: 50px) {
  body {
    font-size: 1.2rem;
  }
}

html {
  font-size: 1.2rem;
}
```
Output:
```css
@media (min-width: 50px) {
  body {
    font-size: 1.2rem;
  }
}

html {
  font-size: 23.04px;
  font-size: 1.2rem;
}
```
