### ISSUE TITLE
calc is not resolving mixed values

### ISSUE THREAD

**Issue by mrchief** [MoOx/postcss-cssnext#410]
**postcss.config.js**

```js
module.exports = (ctx) => ({
    sourceMap: true,
    plugins: [
      require('postcss-import')(),
      require('postcss-url')(),
      require('postcss-cssnext')({
        browsers: ['ie >= 8', 'last 2 versions'],
        warnForDuplicates: false
      }),
      // add additional plugins here
      require('cssnano')({ zindex: false }),
      require('postcss-browser-reporter')(),
      require('postcss-reporter')()
    ],
  }
);
```

**webpack config**

```js
{
  test: /\.css$/,
  loader: ExtractTextPlugin.extract({
    fallback: 'style',
    use: [
      {
        loader: 'css',
        options: {
          importLoaders: 1,
          sourceMap: true,
          modules: CSSModules,
          // "context" and "localIdentName" need to be the same with server config,
          // or the style will flick when page first loaded
          context: path.join(process.cwd(), './src'),
          localIdentName: isDev ? '[name]__[local].[hash:base64:5]' : '[hash:base64:5]',
          minimize: !isDev
        }
      },
      {
        loader: 'postcss'
      }
    ]
  })
}
```

**css**

```css
@import './_variables';

:global(.form .form-group > label) {
  font-size: calc(var(--font-size-base) - 3);
  font-weight: var(--font-weight-bold);
  color: var(--blue);
  text-transform: uppercase;
  letter-spacing: 1px;
}
```

**variables**

```css
:root {
  --blue: #02a3d5; /* "Berg Blue" */
  --font-size-base: 15px;
  --font-weight-bold: 900;
}
```

**output**

![image](https://user-images.githubusercontent.com/781818/29228744-0971bfaa-7ea9-11e7-97e9-09090da1adb3.png)

Using Webpack 3, Node 8 and package versions are:

```
    "css-loader": "^0.28.4",
    "cssnano": "^3.10.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "postcss": "^6.0.8",
    "postcss-browser-reporter": "^0.5.0",
    "postcss-cssnext": "^3.0.2",
    "postcss-import": "^10.0.0",
    "postcss-loader": "^2.0.6",
    "postcss-reporter": "^5.0.0",
    "postcss-url": "^7.1.1",
```
