### ISSUE TITLE
Not working with style-loader

### ISSUE THREAD

**Issue by igor-ribeiro** [MoOx/postcss-cssnext#418]
I'm using `style-loader` and it generates multiple `<style>` tags. I have 2 files:
```css
/* theme.css */
:root {
  --text-color: red;
}

/* App.css */
.App {
  color: var(--text-color);
}
```
The `cssnext` removes the `theme.css` tag and doesn't apply the variable value.

With `cssnext`:
![image](https://user-images.githubusercontent.com/5148753/31090104-dd656554-a77c-11e7-8633-68c3bfc21240.png)

Without `cssnext`:
![image](https://user-images.githubusercontent.com/5148753/31090135-f4411b7e-a77c-11e7-900a-918d82182a08.png)

It warns: **./src/App.css (Emitted value instead of an instance of Error) postcss-custom-properties. variable '--text-color' is undefined and used without a fallback**
