### ISSUE TITLE
Concatenating selector name with nesting seems no longer working

### ISSUE THREAD

**Issue by japboy** [MoOx/postcss-cssnext#421]
i think this was possible until updating to postcss 6 & cssnext 3. but it doesnt get transpiled properly anymore. is this known issue?

```css
.another_class {
  color: green;

  &_emphasized {
    color: red;
    font-weight: bolder;
  }
}

/* .after transpiled to css (with postcss 5.x & cssnext 2.x) */

.another_class {
  color: green;
}

.another_class_emphasized {
  color: red;
  font-weight: bolder;
}
```

any helps would be appreciated. thanks.
