### ISSUE TITLE
Add `image-set()` support

### ISSUE THREAD

**Issue by Grawl** [MoOx/postcss-cssnext#43]
Hey, awesome postprocessor! Love it. But will be provided such things like `image-set()`? I just seen @pepelsbey' [presentation](http://pepelsbey.net/pres/clear-and-sharp/?full#34) and realized that we can to do it with existing `@media` queries.

Like so:

`source.css`

``` css
E {
    background-image: url(picture.png);
    background-image: image-set(
        url(small.jpg) 1x,
        url(medium.jpg) 2x);
    }
```

`dist.css`

``` css
E {
    background-image: url(picture.png);
}
@media (min-resolution: 1dppx) {
    E {
        background-image: url(small.jpg)
    }
}
@media (min-resolution: 2dppx) {
    E {
        background-image: url(medium.jpg)
    }
}
```
