### ISSUE TITLE
Round issue

### ISSUE THREAD

**Issue by MoOx** [MoOx/postcss-cssnext#45]
``` css
:root {
  --fontSize: 3rem;
}

body { font-size: calc(var(--fontSize) * 1.2); }
```

gives

``` css
body { font-size: 3.5999999999999996rem; }
```
