### ISSUE TITLE
Support CSS nesting

### ISSUE THREAD

**Issue by MoOx** [MoOx/postcss-cssnext#80]
I am opening this issue just for people who want to follow the evolution of @tabatkins unofficial draft

http://tabatkins.github.io/specs/css-nesting/

If this become a official draft, we might consider adding this into @postcss parser and create a plugin to transform that.
We also might consider possible side effects.

**Comment by bloodyowl** [comment]
yeah … even if intuitively I'd advice against it, we need to support this if we're keeping cssnext's motto.
plus they're edge use-cases (like markup you don't control, code highlight, markdown parsed …)

**Comment by ShaggyDude** [comment]
Please support this either way. it just makes sense!

**Comment by MoOx** [comment]
It seems like postcss already parse the snippet below (I just tested in the playground, it gives the same result without exception). Probably a good side effect of the parser.

```css
div, p {
    font-size: 10px;
    {.keyword {color: green;}}
    {.constant {
      color: red;
      background-color: green;
      {&:hover::after { content: " [" attr(value) "]";}}
    }}
  }
```

So we should be able to handle that. We need to create a postcss-nesting and use it under stage 0 (ref #100)

**Comment by ai** [comment]
@MoOx awesome. And what AST is generated? Rule with empty selector?

**Comment by MoOx** [comment]
No idea, I will check that really soon and tell you :)

**Comment by crhallberg** [comment]
Would you be able to nest @media queries according to your draft?

```css
.column {
  width: 300px;
  {@media (max-width: 500px) {
    width: auto;
  }}
}
```

```css
.column {width: 300px;}
@media (max-width: 500px) {
  .column {width: auto;}
}
```

**Comment by MoOx** [comment]
Probably more something like

```css
.column {
  width: 300px;
  {@media (max-width: 500px) {&{
    width: auto;
  }}}
}
```

poke @tabatkins

**Comment by crhallberg** [comment]
Makes sense!

**Comment by MoOx** [comment]
omg. @jonathantneal did it https://github.com/jonathantneal/postcss-nesting
Releasing it in 1.8.0 right now.

**Comment by MoOx** [comment]
Well I need to handle #100 so I guess it will take more than 5min ;)

**Comment by jonathanKingston** [comment]
@MoOx did you mention things that were drafts would be flagged?

Also worth pointing you all to this thread as a discussion of this topic:
http://discourse.specifiction.org/t/css-nesting-specification/839/14

**Comment by jonathanKingston** [comment]
Ignore my flag comment as #100 is about that sorry.

**Comment by tabatkins** [comment]
At-rules don't require anything special to be nested.  They're not ambiguous with property grammar, so when they're defined to be nestable, they'll be able to just go directly into the rule block.

And I'm thinking of messing with the syntax more, so definitely keep this in the "experimental" category.

**Comment by MoOx** [comment]
@jonathantneal feel free to submit a pr to postcss-cssnext ;)

**Comment by fingermark** [comment]
I don't get the lack of nesting.  I am trying CSS Modules for the first time.  I'm making a nav menu and it's nice to be able to do this:

```
.nav {
  ...
  li {
    ...
    a {
      ...
      &:hover
    }
    ul.sub {
      li {
        ..
        a {
          ..
        }
      }
    }
  }
}
```

**Comment by jonathantneal** [comment]
I’ve submitted a PR for this. @fingermark, please note that native nesting will not exactly work like Sass nesting. http://tabatkins.github.io/specs/css-nesting/

If you’re coming from Sass, the easiest way to consider the changes is like this: Always use the `&`, and prefix the nested rule with `@nest`.

```css
a {
  @nest span {
    text-decoration: none;
  }
}
```
